feat: Generate Methods in API docs. Bug
* Run:
```
./node_modules/.bin/tsc packages/types/src/Metadata-md.ts; node packages/types/src/Metadata-md.js;
yarn run build; yarn gitbook serve
```
* It should generate docs/METHODS.md (see Bugs below)
* It should be viewable at http://localhost:4000/METHODS.html (see Bugs below)

Bugs:
1) Gitbooks generates METHODS.html from the METHODS.md, and there's a link to it in the SUMMARY.md file, but is not formatting it correctly.

2) It generates the following error for some reason all of a sudden. Initially it was working correctly.

```
/Users/me/code/src/polkadot-js/api/packages/types/src/codec/Compact.js:27
var MAX_U8 = new bn_js_1["default"](2).pow(new bn_js_1["default"](8 - 2)).subn(1);
             ^

TypeError: bn_js_1.default is not a constructor
    at Object.<anonymous> (/Users/scon/code/src/polkadot-js/api/packages/types/src/codec/Compact.js:27:14)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/scon/code/src/polkadot-js/api/packages/types/src/codec/Vector.js:22:17)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
```