refactor: Remove promises/05 & 07, and rx/05 & 07. See details for reasoning.
* Removed promises/05_read_storage since api.query.session is no longer available

```
TypeError: Cannot read property 'validators' of undefined
    at main (/Users/me/code/src/polkadot-js/api/docs/examples/promise/05_read_storage/index.js:15:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

* Removed rx/05_read_storage since api.query.session is no longer available

```
/Users/me/code/src/polkadot-js/api/docs/examples/rx/05_read_storage/node_modules/rxjs/internal/util/hostReportError.js:4
    setTimeout(function () { throw err; });
                             ^

TypeError: Cannot read property 'validators' of undefined
    at validatorsWithBalance (/Users/me/code/src/polkadot-js/api/docs/examples/rx/05_read_storage/index.js:12:28)
    at SwitchMapSubscriber.api.pipe.switchMap [as project] (/Users/me/code/src/polkadot-js/api/docs/examples/rx/05_read_storage/index.js:44:13)
    at SwitchMapSubscriber._next (/Users/me/code/src/polkadot-js/api/docs/examples/rx/05_read_storage/node_modules/rxjs/internal/operators/switchMap.js:49:27)
    at SwitchMapSubscriber.Subscriber.next (/Users/me/code/src/polkadot-js/api/docs/examples/rx/05_read_storage/node_modules/rxjs/internal/Subscriber.js:67:18)
    at /Users/me/code/src/polkadot-js/api/docs/examples/rx/05_read_storage/node_modules/rxjs/internal/util/subscribeToPromise.js:7:24
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

* Removed promises/07_transfer_dots since produces error:

```
ExtError: Unable to determine type from '::Type'
    at assert (/Users/me/code/src/polkadot-js/api/docs/examples/promise/07_transfer_dots/node_modules/@polkadot/util/assert.js:44:9)
    at getTypeClass (/Users/me/code/src/polkadot-js/api/docs/examples/promise/07_transfer_dots/node_modules/@polkadot/types/codec/createType.js:148:20)
    at Method.filterOrigin.reduce (/Users/me/code/src/polkadot-js/api/docs/examples/promise/07_transfer_dots/node_modules/@polkadot/types/Method.js:136:49)
    at Array.reduce (<anonymous>)
    at Function.getArgsDef (/Users/me/code/src/polkadot-js/api/docs/examples/promise/07_transfer_dots/node_modules/@polkadot/types/Method.js:132:38)
    at Function.decodeMethod (/Users/me/code/src/polkadot-js/api/docs/examples/promise/07_transfer_dots/node_modules/@polkadot/types/Method.js:92:30)
    at new Method (/Users/me/code/src/polkadot-js/api/docs/examples/promise/07_transfer_dots/node_modules/@polkadot/types/Method.js:45:28)
    at extrinsicFn (/Users/me/code/src/polkadot-js/api/docs/examples/promise/07_transfer_dots/node_modules/@polkadot/extrinsics/utils/createUnchecked.js:32:15)
    at Object.decorated [as transfer] (/Users/me/code/src/polkadot-js/api/docs/examples/promise/07_transfer_dots/node_modules/@polkadot/api/promise/index.js:207:76)
    at main (/Users/me/code/src/polkadot-js/api/docs/examples/promise/07_transfer_dots/index.js:27:36)
```

* Removed rx/07_transfer_dots since produces error:

```
/Users/me/code/src/polkadot-js/api/docs/examples/rx/07_transfer_dots/node_modules/rxjs/internal/util/hostReportError.js:4
    setTimeout(function () { throw err; });
                             ^

ExtError: Unable to determine type from '::Type'
    at assert (/Users/me/code/src/polkadot-js/api/docs/examples/rx/07_transfer_dots/node_modules/@polkadot/util/assert.js:44:9)
    at getTypeClass (/Users/me/code/src/polkadot-js/api/docs/examples/rx/07_transfer_dots/node_modules/@polkadot/types/codec/createType.js:148:20)
    at Method.filterOrigin.reduce (/Users/me/code/src/polkadot-js/api/docs/examples/rx/07_transfer_dots/node_modules/@polkadot/types/Method.js:136:49)
    at Array.reduce (<anonymous>)
    at Function.getArgsDef (/Users/me/code/src/polkadot-js/api/docs/examples/rx/07_transfer_dots/node_modules/@polkadot/types/Method.js:132:38)
    at Function.decodeMethod (/Users/me/code/src/polkadot-js/api/docs/examples/rx/07_transfer_dots/node_modules/@polkadot/types/Method.js:92:30)
    at new Method (/Users/me/code/src/polkadot-js/api/docs/examples/rx/07_transfer_dots/node_modules/@polkadot/types/Method.js:45:28)
    at extrinsicFn (/Users/me/code/src/polkadot-js/api/docs/examples/rx/07_transfer_dots/node_modules/@polkadot/extrinsics/utils/createUnchecked.js:32:15)
    at Object.decorated [as transfer] (/Users/me/code/src/polkadot-js/api/docs/examples/rx/07_transfer_dots/node_modules/@polkadot/api/rx/index.js:207:76)
    at SwitchMapSubscriber.api.rpc.chain.getBlockHash.pipe.switchMap [as project] (/Users/me/code/src/polkadot-js/api/docs/examples/rx/07_transfer_dots/index.js:36:20)
error Command failed with exit code 1.
```